# YAML/YML file to create a playbook to configure nnginx in our web instance
---
# it starts with three dashes

# add the name of the host/instance/vm
- hosts: app

# collect logs or gather facts -
  gather_facts: yes

# we need admin access to install anything
  become: true

  tasks:
  - name: Installing Nginx web-server in our app machine
    apt: pkg=nginx state=present

  - name: Copy app folder from local to web node
    synchronize:
      src: /home/ubuntu/app/
      dest: ~/app/

  - name: Add nodejs apt key
    apt_key:
      url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
      state: present

  - name: add nodejs 6.x version
    apt_repository:
      repo: deb https://deb.nodesource.com/node_6.x bionic main
      update_cache: yes

  - name: Install nodejs
    apt: pkg=nodejs state=present

  - name: Install npm
    apt: pkg=npm state=present